#!/bin/sh

CONFIG=/etc/zram-activator.conf
ZRAM_SIZE="$(grep MemTotal /proc/meminfo | grep -E --only-matching '[[:digit:]]+')KiB"
ZRAM_ALGORITHM="zstd"
ZRAM_STREAMS="$(nproc)"
ZRAM_PRIORITY=100

# source global config if present
[ -r $CONFIG ] && . $CONFIG

start() {
	echo "loading zram module"
	modprobe zram

	echo "creating zram device"
	zramctl /dev/zram0 --algorithm $ZRAM_ALGORITHM --size $ZRAM_SIZE

	echo "creating swap"
	mkswap -U clear /dev/zram0

	echo "activating swap"
	swapon --discard --priority $ZRAM_PRIORITY /dev/zram0

	echo "swap on zram activated"
}

stop() {
	echo "desactivating swap"
	swapoff /dev/zram0

	echo "disabling zram module"
	modprobe -r zram
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
